timezone: "Etc/UTC"

packages_base:
  - curl
  - wget
  - git
  - htop
  - ufw
  - jq
  - unzip
  - ca-certificates

docker_users:
  - ubuntu

docker_daemon_opts:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "5"
  storage-driver: "overlay2"

ufw_allow_tcp:
  - 22
  - 80
  - 443

enable_unattended_upgrades: true
swap_disable: false
